# -*- coding: utf-8 -*-
"""
@Time ： 2022-09-10 23:59
@Auth ： 小胡
@File ：test_receiving_trustee.py
@IDE ：PyCharm
@Motto：ABC(Always Be Coding)

"""
import pytest
import requests

from RWX_ERPH5_接口测试.test_case.base import Base


class TestPurchaseOrder(Base):
	params = {}
	def test_purchase_order(self,user_login):
		url = 'http://localhost/HHERP/CarpaServerScheme/CarpaServerScheme.Bill.PassVchBillService.ajax/SaveBillData '
		headers = {
			"Cookie": f"BS0518=00000; BS0513=00000; LoginDataBase=BS0518; ASP.NET_SessionId={self.cookie}"
		}
		data = {
			"billSaveState": 3,
			"billData": {
				"guid": "6ece3b40-2eac-457e-ad4f-3dab635e24ec",
				"vchcode": 0,
				"date": "2022-09-10",
				"number": "JHD-2022-09-10-001",
				"vchtype": 7,
				"hightauditstatus": 0,
				"newnumberflag": None,
				"nonecreatenumberflag": None,
				"summary": "从【单位1】订货购进【库存商品-全月-非批次】等：职员1",
				"comment": "",
				"btypeid": "00001",
				"zctypeid": "",
				"etypeid": "00001",
				"ktypeid": "00001",
				"ktypeid2": "",
				"atypeid": "",
				"ifcheck": "",
				"checke": "",
				"period": 0,
				"accounte": "",
				"inputno": "00000",
				"postno": "",
				"draft": 0,
				"redword": "T",
				"attach": 0,
				"billtype": "",
				"gatheringdate": "2022-09-10",
				"projectid": "00001",
				"prtypeid": "",
				"vipcardid": 0,
				"vipdiscount": 0,
				"defdiscount": 0,
				"defaulttax": 0,
				"total": 1,
				"invocetag": 0,
				"lsfull": 0,
				"fromordercode": 0,
				"feebtypeid": "",
				"savecardid": 0,
				"isretail": 0,
				"fctypeid": "00001",
				"fcrate": 1,
				"isfcauto": 0,
				"olddata": None,
				"wtypeid": "",
				"wgtypeid": "",
				"pmtypeid": "00001",
				"isbranchbill": 0,
				"dontpush": 0,
				"vsfdata": {
					"xw_vsf1_name": "",
					"xw_vsf1_value": "",
					"xw_vsf2_name": "",
					"xw_vsf2_value": "",
					"xw_vsf3_name": "",
					"xw_vsf3_value": "",
					"xw_vsf4_name": "",
					"xw_vsf4_value": "",
					"xw_vsf5_name": "",
					"xw_vsf5_value": "",
					"xw_vsf6_name": "",
					"xw_vsf6_value": "",
					"xw_vsf7_name": "",
					"xw_vsf7_value": "",
					"xw_vsf8_name": "",
					"xw_vsf8_value": "",
					"xw_vsf9_name": "",
					"xw_vsf9_value": "",
					"xw_vsf10_name": "",
					"xw_vsf10_value": ""
				},
				"yearperiod": 1,
				"macaddress": "errmac",
				"province": "",
				"city": "",
				"region": "",
				"address": "",
				"btypeholder": "",
				"btypetel": "",
				"details": [{
					"rowid": "",
					"colrowno": 1,
					"modivchcode": 0,
					"vchcode": 0,
					"atypeid": "0000100001",
					"btypeid": "00001",
					"etypeid": "00001",
					"ktypeid": "00001",
					"ktypeid2": "",
					"ptypeid": "00003",
					"kwtypeid": "",
					"qty": 1,
					"discount": 1,
					"discountprice": 1,
					"costtotal": 0,
					"costprice": 0,
					"blockno": "",
					"goodsorderid": -9999,
					"price": 1,
					"total": 1,
					"prodate": "",
					"usefulenddate": "",
					"taxprice": 1,
					"taxtotal": 0,
					"comment": "",
					"date": "2022-09-10",
					"usedtype": 1,
					"period": 0,
					"tax_total": 1,
					"tax": 0,
					"discounttotal": 1,
					"assqty": 1,
					"assprice": 1,
					"assdiscountprice": 1,
					"asstaxprice": 1,
					"unitrate": 1,
					"vchtype": 7,
					"costmode": 4,
					"unit": 0,
					"ordercode": 0,
					"orderdlycode": 0,
					"invocetotal": 0,
					"projectid": "00001",
					"retailprice": 0,
					"handinputzero": 0,
					"pstatus": 0,
					"vipcardid": 0,
					"promovchcode": 0,
					"feetotal": 0,
					"stufftotal": 0,
					"mentotal": 0,
					"produretotal": 0,
					"inprice": 0,
					"intotal": 0,
					"sideqty": 0,
					"pgmancode": 0,
					"snmancode": 0,
					"pjobmancode": 0,
					"pgholqty": 0,
					"pgholinqty": 0,
					"dlyorder": 0,
					"orderuniqueid": "",
					"goodsbatchid": "",
					"upnumber": 0,
					"ubarcode": "003",
					"fctypeid": "00001",
					"fcrate": 1,
					"fctotal": 1,
					"olddata": None,
					"sltypeid": "",
					"jhdate": "2022-09-10",
					"yearperiod": 1,
					"ordervchtype": 0,
					"olddlyorder": 0,
					"forceover": 0,
					"lctotal": 1,
					"lcprice": 1,
					"bomtype": 0,
					"bomvchcode": 0,
					"customer": "",
					"fcdata": {
						"rowid": "",
						"colrowno": 1,
						"modivchcode": 0,
						"vchcode": 0,
						"atypeid": "0000100001",
						"btypeid": "00001",
						"etypeid": "00001",
						"ktypeid": "00001",
						"ktypeid2": "",
						"ptypeid": "00003",
						"kwtypeid": "",
						"qty": 1,
						"discount": 1,
						"discountprice": 1,
						"costtotal": 0,
						"costprice": 0,
						"blockno": "",
						"goodsorderid": -9999,
						"price": 1,
						"total": 1,
						"prodate": "",
						"usefulenddate": "",
						"taxprice": 1,
						"taxtotal": 0,
						"comment": "",
						"date": "2022-09-10",
						"usedtype": 1,
						"period": 0,
						"tax_total": 1,
						"tax": 0,
						"discounttotal": 1,
						"assqty": 1,
						"assprice": 1,
						"assdiscountprice": 1,
						"asstaxprice": 1,
						"unitrate": 1,
						"vchtype": 7,
						"costmode": 4,
						"unit": 0,
						"ordercode": 0,
						"orderdlycode": 0,
						"invocetotal": 0,
						"projectid": "00001",
						"retailprice": 0,
						"handinputzero": 0,
						"pstatus": 0,
						"vipcardid": 0,
						"promovchcode": 0,
						"feetotal": 0,
						"stufftotal": 0,
						"mentotal": 0,
						"produretotal": 0,
						"inprice": 0,
						"intotal": 0,
						"sideqty": 0,
						"pgmancode": 0,
						"snmancode": 0,
						"pjobmancode": 0,
						"pgholqty": 0,
						"pgholinqty": 0,
						"dlyorder": 0,
						"orderuniqueid": "",
						"goodsbatchid": "",
						"upnumber": 0,
						"ubarcode": "003",
						"fctypeid": "00001",
						"fcrate": 1,
						"fctotal": 1,
						"olddata": None,
						"sltypeid": "",
						"jhdate": "2022-09-10",
						"yearperiod": 1,
						"ordervchtype": 0,
						"olddlyorder": 0,
						"forceover": 0,
						"lctotal": 1,
						"lcprice": 1,
						"bomtype": 0,
						"bomvchcode": 0,
						"customer": ""
					}
				}],
				"accountdetails": [],
				"billopenstate": 0,
				"billsavestate": 3,
				"savepplist": None
			}
		}

		res = requests.post(url = url,json=data,headers=headers)
		print(res.json())
	#创建进货单
	# def test_create_purchase(self):
	# 	url = 'http://localhost/HHERP/CarpaServerScheme/CarpaServerScheme.Bill.PassVchBillService.ajax/CreateBillData '
	# 	headers = {
	# 		"Cookie": f"BS0518=00000; BS0513=00000; LoginDataBase=BS0518; ASP.NET_SessionId={self.cookie}"
	# 	}
	# 	data = {
	# 		"billModel": {
	# 			"comment": "",
	# 			"btypeid": "00001",
	# 			"zctypeid": "",
	# 			"etypeid": "00001",
	# 			"ktypeid": "00001",
	# 			"ktypeid2": "",
	# 			"atypeid": "",
	# 			"ifcheck": "1",
	# 			"checke": "",
	# 			"period": 0,
	# 			"accounte": "",
	# 			"inputno": "00000",
	# 			"postno": "00000",
	# 			"draft": 1,
	# 			"redword": "T",
	# 			"attach": 0,
	# 			"billtype": 0,
	# 			"gatheringdate": "",
	# 			"projectid": "00001",
	# 			"prtypeid": None,
	# 			"vipcardid": None,
	# 			"vipdiscount": None,
	# 			"defdiscount": None,
	# 			"defaulttax": 0,
	# 			"total": 1.0000000000,
	# 			"invocetag": 0,
	# 			"lsfull": 0,
	# 			"fromordercode": 0,
	# 			"feebtypeid": "",
	# 			"savemenid": None,
	# 			"savecardid": None,
	# 			"isretail": None,
	# 			"yearperiod": 1,
	# 			"details": [{
	# 				"atypeid": "0000100001",
	# 				"btypeid": "00001",
	# 				"etypeid": "",
	# 				"ktypeid": "00001",
	# 				"ktypeid2": "",
	# 				"ptypeid": "00003",
	# 				"kwtypeid": "",
	# 				"qty": 1,
	# 				"discount": 1.0000000000,
	# 				"discountprice": 1.0000000000,
	# 				"costtotal": 0.0000000000,
	# 				"costprice": 0.0000000000,
	# 				"blockno": "",
	# 				"goodsorderid": -9999,
	# 				"price": 1.0000000000,
	# 				"total": 1.0000000000,
	# 				"prodate": "",
	# 				"usefulenddate": "",
	# 				"taxprice": 0,
	# 				"taxtotal": 0.0000000000,
	# 				"comment": "JHD-2022-09-10-001;",
	# 				"date": "0001-01-01",
	# 				"usedtype": "1",
	# 				"period": 0,
	# 				"tax_total": 0,
	# 				"tax": 0,
	# 				"discounttotal": 1.0000000000,
	# 				"assqty": 0,
	# 				"assprice": 0,
	# 				"assdiscountprice": 0,
	# 				"asstaxprice": 0,
	# 				"unitrate": 1,
	# 				"costmode": 4,
	# 				"unit": 0,
	# 				"invocetotal": 0.0000000000,
	# 				"projectid": "",
	# 				"retailprice": 0,
	# 				"handinputzero": 0,
	# 				"pstatus": 0,
	# 				"vipcardid": 0,
	# 				"promovchcode": 0,
	# 				"feetotal": 0,
	# 				"stufftotal": 0,
	# 				"mentotal": 0,
	# 				"produretotal": 0,
	# 				"inprice": 0,
	# 				"intotal": 0,
	# 				"sideqty": 0.0000000000,
	# 				"pgmancode": "0",
	# 				"snmancode": "0",
	# 				"kwmancode": "0",
	# 				"pjobmancode": "0",
	# 				"pgholqty": 0.0000000000,
	# 				"pgholinqty": 0.0000000000,
	# 				"dlyorder": 3,
	# 				"orderuniqueid": "",
	# 				"goodsbatchid": "",
	# 				"upnumber": 0,
	# 				"ubarcode": "003",
	# 				"sltypeid": "",
	# 				"vchcode": 0,
	# 				"taxrate": 0.0000000000,
	# 				"hantaxprice": 1.0000000000,
	# 				"hantaxtotal": 1.0000000000,
	# 				"vchmemo": "",
	# 				"redword": "F ",
	# 				"olddlyorder": 0,
	# 				"forceover": 0,
	# 				"pstutas": "",
	# 				"toqty": 0.0000000000000000,
	# 				"uname": "个",
	# 				"urate": 1,
	# 				"bcode": "",
	# 				"xw_dsf1": "",
	# 				"xw_dsf2": "",
	# 				"xw_dsf3": "",
	# 				"xw_dsf4": "",
	# 				"xw_dsf5": "",
	# 				"xw_dsf6": "",
	# 				"xw_dsf7": "",
	# 				"xw_dsf8": "",
	# 				"xw_dsf9": "",
	# 				"xw_dsf10": "",
	# 				"ptypetype": "0",
	# 				"ordercode": 3,
	# 				"orderdlycode": 3,
	# 				"ordervchtype": 7,
	# 				"jhdate": "2022-09-10",
	# 				"customer": "",
	# 				"bomtype": 0,
	# 				"bomvchcode": 0,
	# 				"bfullname": None,
	# 				"bomfullname": "",
	# 				"__rowIndex": 0,
	# 				"vchtype": 34,
	# 				"unit2": "1箱=2盒=10个",
	# 				"pfullname": "库存商品-全月-非批次",
	# 				"pusercode": "003",
	# 				"mixqty": "1个",
	# 				"baseqty": "1",
	# 				"secqty1": "0.2",
	# 				"secqty2": "0.1",
	# 				"kusercode": "01",
	# 				"kfullname": "仓库1",
	# 				"fcrate": 1,
	# 				"lctotal": 1,
	# 				"lcdiscounttotal": 1,
	# 				"lctaxtotal": 0,
	# 				"lchantaxtotal": 1,
	# 				"databind_gridname": "Grid",
	# 				"forceovertext": "否",
	# 				"ptypeid_standard": "",
	# 				"ptypeid_type": "",
	# 				"ptypeid_area": "",
	# 				"ptypeid_uassrate1": "5",
	# 				"ptypeid_uassrate2": "10",
	# 				"modivchcode": 0,
	# 				"isrelation": 1,
	# 				"fctypeid": "00001",
	# 				"fctotal": 1,
	# 				"sourcedata": {
	# 					"ktypeid": "00001",
	# 					"sltypeid": "",
	# 					"vchcode": 3,
	# 					"ptypeid": "00003",
	# 					"btypeid": "00001",
	# 					"kwtypeid": "",
	# 					"atypeid": "0000100001",
	# 					"qty": 1.0000000000,
	# 					"sideqty": 0.0000000000,
	# 					"price": 1.0000000000,
	# 					"total": 1.0000000000,
	# 					"discount": 1.0000000000,
	# 					"discountprice": 1.0000000000,
	# 					"discounttotal": 1.0000000000,
	# 					"taxrate": 0.0000000000,
	# 					"taxtotal": 0.0000000000,
	# 					"hantaxprice": 1.0000000000,
	# 					"hantaxtotal": 1.0000000000,
	# 					"usedtype": "1",
	# 					"vchmemo": "",
	# 					"prodate": "",
	# 					"usefulenddate": "",
	# 					"blockno": "",
	# 					"costprice": 0.0000000000,
	# 					"costtotal": 0.0000000000,
	# 					"goodsorderid": -9999,
	# 					"costmode": 4,
	# 					"redword": "F ",
	# 					"unit": 0,
	# 					"invocetotal": 0.0000000000,
	# 					"dlyorder": 3,
	# 					"olddlyorder": 3,
	# 					"forceover": 0,
	# 					"pstutas": "",
	# 					"toqty": 0.0000000000000000,
	# 					"ubarcode": "003",
	# 					"uname": "个",
	# 					"urate": 1,
	# 					"bcode": "",
	# 					"pgholqty": 0.0000000000,
	# 					"pgholinqty": 0.0000000000,
	# 					"xw_dsf1": "",
	# 					"xw_dsf2": "",
	# 					"xw_dsf3": "",
	# 					"xw_dsf4": "",
	# 					"xw_dsf5": "",
	# 					"xw_dsf6": "",
	# 					"xw_dsf7": "",
	# 					"xw_dsf8": "",
	# 					"xw_dsf9": "",
	# 					"xw_dsf10": "",
	# 					"pgmancode": "0",
	# 					"snmancode": "0",
	# 					"kwmancode": "0",
	# 					"pjobmancode": "0",
	# 					"ptypetype": "0",
	# 					"ordercode": 0,
	# 					"orderdlycode": 0,
	# 					"ordervchtype": 0,
	# 					"jhdate": "2022-09-10",
	# 					"promovchcode": 0,
	# 					"goodsbatchid": "",
	# 					"customer": "",
	# 					"bomtype": 0,
	# 					"bomvchcode": 0,
	# 					"bfullname": None,
	# 					"bomfullname": "",
	# 					"__rowIndex": 0,
	# 					"vchtype": 7,
	# 					"unit2": "1箱=2盒=10个",
	# 					"pfullname": "库存商品-全月-非批次",
	# 					"pusercode": "003",
	# 					"mixqty": "1个",
	# 					"baseqty": "1",
	# 					"secqty1": "0.2",
	# 					"secqty2": "0.1",
	# 					"kusercode": "01",
	# 					"kfullname": "仓库1",
	# 					"fcrate": 1,
	# 					"lctotal": 1,
	# 					"lcdiscounttotal": 1,
	# 					"lctaxtotal": 0,
	# 					"lchantaxtotal": 1,
	# 					"databind_gridname": "Grid",
	# 					"forceovertext": "否",
	# 					"ptypeid_standard": "",
	# 					"ptypeid_type": "",
	# 					"ptypeid_area": "",
	# 					"ptypeid_uassrate1": "5",
	# 					"ptypeid_uassrate2": "10",
	# 					"comment": "JHD-2022-09-10-001;",
	# 					"pstatus": 0
	# 				},
	# 				"dsfdata": {
	# 					"xw_dsf1": "",
	# 					"xw_dsf2": "",
	# 					"xw_dsf3": "",
	# 					"xw_dsf4": "",
	# 					"xw_dsf5": "",
	# 					"xw_dsf6": "",
	# 					"xw_dsf7": "",
	# 					"xw_dsf8": "",
	# 					"xw_dsf9": "",
	# 					"xw_dsf10": ""
	# 				},
	# 				"colrowno": 0
	# 			}],
	# 			"vchcode": 0,
	# 			"vchtype": 34,
	# 			"orderauditstate": "-1",
	# 			"requestauditstate": 0,
	# 			"vchtitle": "",
	# 			"billopenstate": 0,
	# 			"number": "JHD-2022-09-10-001",
	# 			"continueprint": False,
	# 			"printcheck": False,
	# 			"ordervchcode": 0,
	# 			"mode": "",
	# 			"fmode": 0,
	# 			"MacAddress": "errmac",
	# 			"iscopy": False,
	# 			"isBalance": False,
	# 			"invoicecode": 0,
	# 			"invoicemode": "",
	# 			"invoicetype": "",
	# 			"isunionquery": False,
	# 			"billbalancemode": 0,
	# 			"isgenerated": 0,
	# 			"isfcauto": 0,
	# 			"isopenfromaudit": False,
	# 			"isbranchbill": 0,
	# 			"dontpush": 0,
	# 			"date": "0001-01-01",
	# 			"summary": "从【单位1】订货购进【库存商品-全月-非批次】等：职员1",
	# 			"redold": "F",
	# 			"inputn": 0,
	# 			"inputno1": "",
	# 			"inputno2": "",
	# 			"inputno3": "",
	# 			"inputno4": "",
	# 			"inputno5": "",
	# 			"deptid": "00001",
	# 			"orderover": 0,
	# 			"todate": "2022-09-10",
	# 			"userover": 0,
	# 			"cashover": 0,
	# 			"avchcode": 0,
	# 			"counttype": 0,
	# 			"comment1": "",
	# 			"comment2": "",
	# 			"comment3": "",
	# 			"savedate": r"\/Date(1662829779270)\/",
	# 			"vchtypestate": 2,
	# 			"auditstate": -1,
	# 			"isreject": 0,
	# 			"fctypeid": "00001",
	# 			"fcrate": 1,
	# 			"fctotal": 1.0000000000,
	# 			"pmtypeid": "00001",
	# 			"province": "",
	# 			"city": "",
	# 			"region": "",
	# 			"address": "",
	# 			"btypeholder": "",
	# 			"btypetel": "",
	# 			"printnum": 0,
	# 			"bfullname": "单位1",
	# 			"busercode": "01",
	# 			"efullname": "职员1",
	# 			"eusercode": "01",
	# 			"dfullname": "部门1",
	# 			"dusercode": "01",
	# 			"dtypeid": "00001",
	# 			"kfullname": "仓库1",
	# 			"kusercode": "01",
	# 			"pmfullname": "项目1",
	# 			"pmusercode": "01",
	# 			"fcname": "人民币",
	# 			"fccode": "RMB",
	# 			"detailsTableName": "BakDlyOrder",
	# 			"accountTableName": "OrderBankCash",
	# 			"preferentialTableName": "DlyAPref",
	# 			"afullname": "",
	# 			"gathertotal": 0,
	# 			"checkover": False,
	# 			"lsretail": None,
	# 			"byryp": None,
	# 			"ispos": None,
	# 			"cardtypeid": None,
	# 			"lsSave": None,
	# 			"extend": None,
	# 			"integral": None,
	# 			"discountcard": None,
	# 			"lsvipprice": None,
	# 			"autoupdate": None,
	# 			"isprintpost": None,
	# 			"newnumberflag": None,
	# 			"nonecreatenumberflag": None,
	# 			"uniqueid": None,
	# 			"retailissave": None,
	# 			"invoicerepeat": None,
	# 			"bomtype": None,
	# 			"bomvchcode": None,
	# 			"scanbomcode": None,
	# 			"cardid": None,
	# 			"mtypeid": "",
	# 			"accountdetails": [],
	# 			"vipaccountdetails": None,
	# 			"preferentotal": None,
	# 			"cardno": "",
	# 			"vipdiscountname": "",
	# 			"vipgather": "",
	# 			"viptotal": "",
	# 			"vipname": "",
	# 			"splittype": 0,
	# 			"isRelation": True,
	# 			"createfromvchcode": 3,
	# 			"createfromvchtype": 7,
	# 			"guid": "3402caec-c54b-4e15-8fee-c8b87a8f1f67",
	# 			"gatherbtypeid": "00001",
	# 			"macaddress": "errmac",
	# 			"billsavestate": 1,
	# 			"ndxlist": None,
	# 			"ppCodeString": "",
	# 			"isCreatePP": 0
	# 		}
	# 	}
	# 	res = requests.post(url=url, json=data, headers=headers)
	# 	print(res.json())
	#保存进货单
	def test_save_purchase(self):
		url = 'http://localhost/HHERP/CarpaServerScheme/CarpaServerScheme.Bill.PassVchBillService.ajax/SaveBillData'
		headers = {
			"Cookie": f"BS0518=00000; BS0513=00000; LoginDataBase=BS0518; ASP.NET_SessionId={self.cookie}"
		}
		data = {
			"billSaveState": 3,
			"billData": {
				"guid": "d61282ff-80a1-4f16-905c-35eb53120c71",
				"vchcode": 0,
				"date": "2022-09-11",
				"number": "JH-2022-09-11-001",
				"vchtype": 34,
				"hightauditstatus": 0,
				"newnumberflag": None,
				"nonecreatenumberflag": None,
				"summary": "从【单位1】购进【库存商品-全月-非批次】等：职员1",
				"comment": "",
				"btypeid": "00001",
				"zctypeid": "",
				"etypeid": "00001",
				"ktypeid": "00001",
				"ktypeid2": "",
				"atypeid": "",
				"ifcheck": "",
				"checke": "",
				"period": 0,
				"accounte": "",
				"inputno": "00000",
				"postno": "00000",
				"draft": 3,
				"redword": "F",
				"attach": 0,
				"billtype": 0,
				"gatheringdate": "0028-05-18",
				"projectid": "00001",
				"prtypeid": "",
				"vipcardid": "",
				"vipdiscount": 0,
				"defdiscount": 0,
				"defaulttax": 0,
				"total": 1,
				"invocetag": 0,
				"lsfull": 0,
				"fromordercode": 0,
				"feebtypeid": "",
				"savecardid": None,
				"isretail": 0,
				"fctypeid": "00001",
				"fcrate": 1,
				"isfcauto": 0,
				"olddata": None,
				"wtypeid": "",
				"wgtypeid": "",
				"pmtypeid": "00001",
				"isbranchbill": 0,
				"dontpush": 0,
				"vsfdata": {
					"xw_vsf1_name": "",
					"xw_vsf1_value": "",
					"xw_vsf2_name": "",
					"xw_vsf2_value": "",
					"xw_vsf3_name": "",
					"xw_vsf3_value": "",
					"xw_vsf4_name": "",
					"xw_vsf4_value": "",
					"xw_vsf5_name": "",
					"xw_vsf5_value": "",
					"xw_vsf6_name": "",
					"xw_vsf6_value": "",
					"xw_vsf7_name": "",
					"xw_vsf7_value": "",
					"xw_vsf8_name": "",
					"xw_vsf8_value": "",
					"xw_vsf9_name": "",
					"xw_vsf9_value": "",
					"xw_vsf10_name": "",
					"xw_vsf10_value": ""
				},
				"modino": "00000",
				"noinvoice": 0,
				"feetype": 0,
				"ispos": None,
				"savemenid": None,
				"macaddress": "errmac",
				"province": "",
				"city": "",
				"region": "",
				"address": "",
				"btypeholder": "",
				"btypetel": "",
				"details": [{
					"rowid": "",
					"colrowno": 1,
					"modivchcode": 0,
					"vchcode": 0,
					"atypeid": "0000100001",
					"btypeid": "00001",
					"etypeid": "00001",
					"ktypeid": "00001",
					"ktypeid2": "",
					"ptypeid": "00005",
					"kwtypeid": "",
					"qty": 1,
					"discount": 1.0000000000,
					"discountprice": 1,
					"costtotal": 0,
					"costprice": 0,
					"blockno": "",
					"goodsorderid": -9999,
					"price": 1,
					"total": 1,
					"prodate": "",
					"usefulenddate": "",
					"taxprice": 1,
					"taxtotal": 0,
					"comment": "",
					"date": "2022-09-10",
					"usedtype": 1,
					"period": 0,
					"tax_total": 1,
					"tax": 0,
					"discounttotal": 1,
					"assqty": 1,
					"assprice": 1,
					"assdiscountprice": 1,
					"asstaxprice": 1,
					"unitrate": 1,
					"vchtype": 34,
					"costmode": 4,
					"unit": 0,
					"ordercode": 0,
					"orderdlycode": 0,
					"invocetotal": 0,
					"projectid": "00001",
					"retailprice": 2,
					"handinputzero": 0,
					"pstatus": 0,
					"vipcardid": 0,
					"promovchcode": 0,
					"feetotal": 0,
					"stufftotal": 0,
					"mentotal": 0,
					"produretotal": 0,
					"inprice": 1,
					"intotal": 1,
					"sideqty": 0,
					"pgmancode": 0,
					"snmancode": 0,
					"pjobmancode": 0,
					"pgholqty": 0,
					"pgholinqty": 0,
					"dlyorder": 0,
					"orderuniqueid": "",
					"goodsbatchid": "",
					"upnumber": 0,
					"ubarcode": "003",
					"fctypeid": "00001",
					"fcrate": 1,
					"fctotal": 1,
					"olddata": None,
					"sltypeid": "",
					"ordervchtype": 0,
					"lctotal": 1,
					"lcprice": 1,
					"fcdata": {
						"rowid": "",
						"colrowno": 1,
						"modivchcode": 0,
						"vchcode": 0,
						"atypeid": "0000100001",
						"btypeid": "00001",
						"etypeid": "00001",
						"ktypeid": "00001",
						"ktypeid2": "",
						"ptypeid": "00003",
						"kwtypeid": "",
						"qty": 1,
						"discount": 1.0000000000,
						"discountprice": 1,
						"costtotal": 0,
						"costprice": 0,
						"blockno": "",
						"goodsorderid": -9999,
						"price": 1,
						"total": 1,
						"prodate": "",
						"usefulenddate": "",
						"taxprice": 1,
						"taxtotal": 0,
						"comment": "",
						"date": "2022-09-10",
						"usedtype": 1,
						"period": 0,
						"tax_total": 1,
						"tax": 0,
						"discounttotal": 1,
						"assqty": 1,
						"assprice": 1,
						"assdiscountprice": 1,
						"asstaxprice": 1,
						"unitrate": 1,
						"vchtype": 34,
						"costmode": 4,
						"unit": 0,
						"ordercode": 0,
						"orderdlycode": 0,
						"invocetotal": 0,
						"projectid": "00001",
						"retailprice": 2.0000000000,
						"handinputzero": 0,
						"pstatus": 0,
						"vipcardid": 0,
						"promovchcode": 0,
						"feetotal": 0,
						"stufftotal": 0,
						"mentotal": 0,
						"produretotal": 0,
						"inprice": 1,
						"intotal": 1,
						"sideqty": 0,
						"pgmancode": 0,
						"snmancode": 0,
						"pjobmancode": 0,
						"pgholqty": 0,
						"pgholinqty": 0,
						"dlyorder": 0,
						"orderuniqueid": "",
						"goodsbatchid": "",
						"upnumber": 0,
						"ubarcode": "003",
						"fctypeid": "00001",
						"fcrate": 1,
						"fctotal": 1,
						"olddata": None,
						"sltypeid": "",
						"ordervchtype": 0,
						"lctotal": 1,
						"lcprice": 1
					}
				}],
				"accountdetails": [{
					"rowid": 1,
					"colrowno": 0,
					"modivchcode": 0,
					"vchcode": 34,
					"ndlyorder": 0,
					"vchtype": 34,
					"atypeid": "000010000300001",
					"btypeid": "00001",
					"etypeid": "00001",
					"ktypeid": "00001",
					"projectid": "00001",
					"date": "2022-09-10",
					"total": 1,
					"ktypeid2": "",
					"ptypeid": "",
					"kwtypeid": "",
					"qty": 0,
					"discount": 0,
					"discountprice": 0,
					"costtotal": 0,
					"costprice": 0,
					"blockno": "",
					"goodsorderid": 0,
					"price": 0,
					"prodate": "",
					"usefulenddate": "",
					"taxprice": 0,
					"taxtotal": 0,
					"comment": "",
					"usedtype": "2",
					"period": 0,
					"tax_total": 0,
					"tax": 0,
					"discounttotal": 0,
					"assqty": 0,
					"assprice": 0,
					"assdiscountprice": 0,
					"asstaxprice": 0,
					"unitrate": 0,
					"costmode": 0,
					"unit": 0,
					"ordercode": 0,
					"orderdlycode": 0,
					"invocetotal": 0,
					"retailprice": 0,
					"handinputzero": 0,
					"pstatus": 0,
					"vipcardid": 0,
					"promovchcode": 0,
					"feetotal": 0,
					"stufftotal": 0,
					"mentotal": 0,
					"produretotal": 0,
					"inprice": 0,
					"intotal": 0,
					"sideqty": 0,
					"pgmancode": 0,
					"snmancode": 0,
					"pgholqty": 0,
					"pgholinqty": 0,
					"dlyorder": 0,
					"oldqty": 0,
					"oldprice": 0,
					"orderuniqueid": "",
					"goodsbatchid": "",
					"upnumber": 0,
					"wxmchid": None,
					"olddata": None,
					"fctypeid": "00001",
					"fcrate": 1,
					"fctotal": 1
				}],
				"billopenstate": 0,
				"billsavestate": 3,
				"savepplist": None
			}
		}
		res = requests.post(url=url, json=data, headers=headers)
		print(res.json())
	#进货换货单
# 	def test_purchase_swap_order(self):
# 		url = 'http://localhost/HHERP/CarpaServerScheme/CarpaServerScheme.Bill.PassVchBillService.ajax/SaveBillData'
# 		headers = {
# 			"Cookie": f"BS0518=00000; BS0513=00000; LoginDataBase=BS0518; ASP.NET_SessionId={self.cookie}"
# 		}
# 		data = {
# 	"billSaveState": 3,
# 	"billData": {
# 		"guid": "2f445309-cba5-46f9-9bfd-466d3055088c",
# 		"vchcode": 0,
# 		"date": "2022-09-10",
# 		"number": "JHH-2022-09-10-001",
# 		"vchtype": 143,
# 		"hightauditstatus": 0,
# 		"newnumberflag": None,
# 		"nonecreatenumberflag": None,
# 		"summary": "向【单位1】换出【库存商品-全月-非批次】等：职员1",
# 		"comment": "",
# 		"btypeid": "00001",
# 		"zctypeid": "",
# 		"etypeid": "00001",
# 		"ktypeid": "00001",
# 		"ktypeid2": "00001",
# 		"atypeid": "",
# 		"ifcheck": "",
# 		"checke": "",
# 		"period": 0,
# 		"accounte": "",
# 		"inputno": "00000",
# 		"postno": "00000",
# 		"draft": 3,
# 		"redword": "F",
# 		"attach": 0,
# 		"billtype": 0,
# 		"gatheringdate": "",
# 		"projectid": "00001",
# 		"prtypeid": "",
# 		"vipcardid": 0,
# 		"vipdiscount": 0,
# 		"defdiscount": 0,
# 		"defaulttax": 0,
# 		"total": "0",
# 		"invocetag": 0,
# 		"lsfull": 0,
# 		"fromordercode": 0,
# 		"feebtypeid": "",
# 		"savecardid": 0,
# 		"isretail": 0,
# 		"fctypeid": "00001",
# 		"fcrate": 1,
# 		"isfcauto": 0,
# 		"olddata": None,
# 		"wtypeid": "",
# 		"wgtypeid": "",
# 		"pmtypeid": "00001",
# 		"isbranchbill": 0,
# 		"dontpush": 0,
# 		"vsfdata": {
# 			"xw_vsf1_name": "",
# 			"xw_vsf1_value": "",
# 			"xw_vsf2_name": "",
# 			"xw_vsf2_value": "",
# 			"xw_vsf3_name": "",
# 			"xw_vsf3_value": "",
# 			"xw_vsf4_name": "",
# 			"xw_vsf4_value": "",
# 			"xw_vsf5_name": "",
# 			"xw_vsf5_value": "",
# 			"xw_vsf6_name": "",
# 			"xw_vsf6_value": "",
# 			"xw_vsf7_name": "",
# 			"xw_vsf7_value": "",
# 			"xw_vsf8_name": "",
# 			"xw_vsf8_value": "",
# 			"xw_vsf9_name": "",
# 			"xw_vsf9_value": "",
# 			"xw_vsf10_name": "",
# 			"xw_vsf10_value": ""
# 		},
# 		"modino": "00000",
# 		"isfull": 0,
# 		"macaddress": "errmac",
# 		"chkpbomitem": 0,
# 		"scanbomcode": 0,
# 		"details": [{
# 			"rowid": "",
# 			"colrowno": 1,
# 			"modivchcode": 0,
# 			"vchcode": 0,
# 			"atypeid": "0000100001",
# 			"btypeid": "00001",
# 			"etypeid": "00001",
# 			"ktypeid": "00001",
# 			"ktypeid2": "",
# 			"ptypeid": "00003",
# 			"kwtypeid": "",
# 			"qty": 1,
# 			"discount": 1.0000000000,
# 			"discountprice": 1,
# 			"costtotal": 0,
# 			"costprice": 0,
# 			"blockno": "",
# 			"goodsorderid": 0,
# 			"price": 1,
# 			"total": 1,
# 			"prodate": "",
# 			"usefulenddate": "",
# 			"taxprice": 1,
# 			"taxtotal": 0,
# 			"comment": "",
# 			"date": "2022-09-10",
# 			"usedtype": 1,
# 			"period": 0,
# 			"tax_total": 1,
# 			"tax": 0,
# 			"discounttotal": 1,
# 			"assqty": 1,
# 			"assprice": 1,
# 			"assdiscountprice": 1,
# 			"asstaxprice": 1,
# 			"unitrate": 1,
# 			"vchtype": 143,
# 			"costmode": 4,
# 			"unit": 0,
# 			"ordercode": 0,
# 			"orderdlycode": 0,
# 			"invocetotal": 0,
# 			"projectid": "00001",
# 			"retailprice": 2,
# 			"handinputzero": 0,
# 			"pstatus": 0,
# 			"vipcardid": 0,
# 			"promovchcode": 0,
# 			"feetotal": 0,
# 			"stufftotal": 0,
# 			"mentotal": 0,
# 			"produretotal": 0,
# 			"inprice": 0,
# 			"intotal": 0,
# 			"sideqty": 0,
# 			"pgmancode": 0,
# 			"snmancode": 0,
# 			"pjobmancode": 0,
# 			"pgholqty": 0,
# 			"pgholinqty": 0,
# 			"dlyorder": 0,
# 			"orderuniqueid": "",
# 			"goodsbatchid": "",
# 			"upnumber": 0,
# 			"ubarcode": "003",
# 			"fctypeid": "00001",
# 			"fcrate": 1,
# 			"fctotal": 1,
# 			"olddata": None,
# 			"sltypeid": "",
# 			"ordervchtype": 0,
# 			"lctotal": 1,
# 			"lcprice": 1,
# 			"fcdata": {
# 				"rowid": "",
# 				"colrowno": 1,
# 				"modivchcode": 0,
# 				"vchcode": 0,
# 				"atypeid": "0000100001",
# 				"btypeid": "00001",
# 				"etypeid": "00001",
# 				"ktypeid": "00001",
# 				"ktypeid2": "",
# 				"ptypeid": "00003",
# 				"kwtypeid": "",
# 				"qty": 1,
# 				"discount": 1.0000000000,
# 				"discountprice": 1,
# 				"costtotal": 0,
# 				"costprice": 0,
# 				"blockno": "",
# 				"goodsorderid": 0,
# 				"price": 1,
# 				"total": 1,
# 				"prodate": "",
# 				"usefulenddate": "",
# 				"taxprice": 1,
# 				"taxtotal": 0,
# 				"comment": "",
# 				"date": "2022-09-10",
# 				"usedtype": 1,
# 				"period": 0,
# 				"tax_total": 1,
# 				"tax": 0,
# 				"discounttotal": 1,
# 				"assqty": 1,
# 				"assprice": 1,
# 				"assdiscountprice": 1,
# 				"asstaxprice": 1,
# 				"unitrate": 1,
# 				"vchtype": 143,
# 				"costmode": 4,
# 				"unit": 0,
# 				"ordercode": 0,
# 				"orderdlycode": 0,
# 				"invocetotal": 0,
# 				"projectid": "00001",
# 				"retailprice": 2.0000000000,
# 				"handinputzero": 0,
# 				"pstatus": 0,
# 				"vipcardid": 0,
# 				"promovchcode": 0,
# 				"feetotal": 0,
# 				"stufftotal": 0,
# 				"mentotal": 0,
# 				"produretotal": 0,
# 				"inprice": 0,
# 				"intotal": 0,
# 				"sideqty": 0,
# 				"pgmancode": 0,
# 				"snmancode": 0,
# 				"pjobmancode": 0,
# 				"pgholqty": 0,
# 				"pgholinqty": 0,
# 				"dlyorder": 0,
# 				"orderuniqueid": "",
# 				"goodsbatchid": "",
# 				"upnumber": 0,
# 				"ubarcode": "003",
# 				"fctypeid": "00001",
# 				"fcrate": 1,
# 				"fctotal": 1,
# 				"olddata": None,
# 				"sltypeid": "",
# 				"ordervchtype": 0,
# 				"lctotal": 1,
# 				"lcprice": 1
# 			}
# 		}, {
# 			"rowid": "",
# 			"colrowno": 1,
# 			"modivchcode": 0,
# 			"vchcode": 0,
# 			"atypeid": "0000100001",
# 			"btypeid": "00001",
# 			"etypeid": "00001",
# 			"ktypeid": "00001",
# 			"ktypeid2": "",
# 			"ptypeid": "00004",
# 			"kwtypeid": "",
# 			"qty": 1,
# 			"discount": 1.0000000000,
# 			"discountprice": 1,
# 			"costtotal": 0,
# 			"costprice": 0,
# 			"blockno": "",
# 			"goodsorderid": 0,
# 			"price": 1,
# 			"total": 1,
# 			"prodate": "",
# 			"usefulenddate": "",
# 			"taxprice": 1,
# 			"taxtotal": 0,
# 			"comment": "",
# 			"date": "2022-09-10",
# 			"usedtype": 2,
# 			"period": 0,
# 			"tax_total": 1,
# 			"tax": 0,
# 			"discounttotal": 1,
# 			"assqty": 1,
# 			"assprice": 1,
# 			"assdiscountprice": 1,
# 			"asstaxprice": 1,
# 			"unitrate": 1,
# 			"vchtype": 143,
# 			"costmode": 4,
# 			"unit": 0,
# 			"ordercode": 0,
# 			"orderdlycode": 0,
# 			"invocetotal": 0,
# 			"projectid": "00001",
# 			"retailprice": 2,
# 			"handinputzero": 0,
# 			"pstatus": 0,
# 			"vipcardid": 0,
# 			"promovchcode": 0,
# 			"feetotal": 0,
# 			"stufftotal": 0,
# 			"mentotal": 0,
# 			"produretotal": 0,
# 			"inprice": 0,
# 			"intotal": 0,
# 			"sideqty": 0,
# 			"pgmancode": 0,
# 			"snmancode": 0,
# 			"pjobmancode": 1,
# 			"pgholqty": 0,
# 			"pgholinqty": 0,
# 			"dlyorder": 0,
# 			"orderuniqueid": "",
# 			"goodsbatchid": "",
# 			"upnumber": 0,
# 			"ubarcode": "004",
# 			"fctypeid": "00001",
# 			"fcrate": 1,
# 			"fctotal": 1,
# 			"olddata": None,
# 			"sltypeid": "",
# 			"ordervchtype": 0,
# 			"lctotal": 1,
# 			"lcprice": 1,
# 			"fcdata": {
# 				"rowid": "",
# 				"colrowno": 1,
# 				"modivchcode": 0,
# 				"vchcode": 0,
# 				"atypeid": "0000100001",
# 				"btypeid": "00001",
# 				"etypeid": "00001",
# 				"ktypeid": "00001",
# 				"ktypeid2": "",
# 				"ptypeid": "00004",
# 				"kwtypeid": "",
# 				"qty": 1,
# 				"discount": 1.0000000000,
# 				"discountprice": 1,
# 				"costtotal": 0,
# 				"costprice": 0,
# 				"blockno": "",
# 				"goodsorderid": 0,
# 				"price": 1,
# 				"total": 1,
# 				"prodate": "",
# 				"usefulenddate": "",
# 				"taxprice": 1,
# 				"taxtotal": 0,
# 				"comment": "",
# 				"date": "2022-09-10",
# 				"usedtype": 2,
# 				"period": 0,
# 				"tax_total": 1,
# 				"tax": 0,
# 				"discounttotal": 1,
# 				"assqty": 1,
# 				"assprice": 1,
# 				"assdiscountprice": 1,
# 				"asstaxprice": 1,
# 				"unitrate": 1,
# 				"vchtype": 143,
# 				"costmode": 4,
# 				"unit": 0,
# 				"ordercode": 0,
# 				"orderdlycode": 0,
# 				"invocetotal": 0,
# 				"projectid": "00001",
# 				"retailprice": 2.0000000000,
# 				"handinputzero": 0,
# 				"pstatus": 0,
# 				"vipcardid": 0,
# 				"promovchcode": 0,
# 				"feetotal": 0,
# 				"stufftotal": 0,
# 				"mentotal": 0,
# 				"produretotal": 0,
# 				"inprice": 0,
# 				"intotal": 0,
# 				"sideqty": 0,
# 				"pgmancode": 0,
# 				"snmancode": 0,
# 				"pjobmancode": 1,
# 				"pgholqty": 0,
# 				"pgholinqty": 0,
# 				"dlyorder": 0,
# 				"orderuniqueid": "",
# 				"goodsbatchid": "",
# 				"upnumber": 0,
# 				"ubarcode": "004",
# 				"fctypeid": "00001",
# 				"fcrate": 1,
# 				"fctotal": 1,
# 				"olddata": None,
# 				"sltypeid": "",
# 				"ordervchtype": 0,
# 				"lctotal": 1,
# 				"lcprice": 1
# 			}
# 		}],
# 		"accountdetails": [],
# 		"billopenstate": 0,
# 		"billsavestate": 3,
# 		"savepplist": None
# 	}
# }
# 		res = requests.post(url=url, json=data, headers=headers)
# 		print(res.json())



if __name__ == '__main__':
    pytest.main(['-sv', __file__])